# This is a configuration file describing the id of the child of each repo
harmoni:
  #bot: ["default"]
  tts: ["default"]
  web: ["default"]
  #stt: ["default"]
  gesture: ["default"]
  #face_detect: ["default"]
hardware:
  #microphone: ["default"]
  #camera: ["default"]
  speaker: ["default"]

pattern:
  idle: ["default"]
  code: ["default"]
  multiple_choice: ["default"]
  display_image: ["default"]
  sentence_repetition: ["default"]
