# Configuration file for the microphone
bot:
  micol_param:
    user_id: "micol_testing_1"
    bot_name: "QTRobot"
    bot_alias: "qt_robot_test"
    region_name: "eu-west-2"
  default_param:
    user_id: "corradopacelli"
    bot_name: "CorryBot"
    bot_alias: "corry"
    region_name: "eu-west-2"

google:
  default_param:
    project_id: "agent1-ewhnht"
    language: "it"
    session_id: "test_bot"
    credential_path: "$(find harmoni_stt)/config/private-keys.json"
  en_param:
    project_id: "interactivecanvas-ee969"
    language: "en"
    session_id: "testing"
    credential_path: "$(find harmoni_bot)/config/private-keys_en.json"
