dialogue:
  default_param:
    trigger_intent: "Hey"
    pattern_scripting: $(find harmoni_pattern)/pattern_scripting/dialogue.json

multiple_choice:
  default_param:
    trigger_intent: "Hey"
    pattern_scripting: $(find harmoni_pattern)/pattern_scripting/multiple_choice.json

type_dialogue:
  default_param:
    trigger_intent: "Hey"
    pattern_scripting: $(find harmoni_pattern)/pattern_scripting/type_dialogue.json

listening:
  default_param:
    trigger_intent: "Hey"
    pattern_scripting: $(find harmoni_pattern)/pattern_scripting/listening.json

mic_test:
  default_param:
    trigger_intent: "Hey"
    pattern_scripting: $(find harmoni_pattern)/pattern_scripting/mic_test.json


speak_test:
  default_param:
    trigger_intent: "Hey"
    pattern_scripting: $(find harmoni_pattern)/pattern_scripting/speak_test.json

context_dialogue:
  default_param:
    trigger_intent: "sono stanca"
    pattern_scripting: $(find harmoni_pattern)/pattern_scripting/context_dialogue.json 
    
system_initiative:
  default_param:
    trigger_intent: "{ \"action\":\"check_log\", \"entity\":\"googlehome8554\", \"type\":\"media_player\"}"
    pattern_scripting: $(find harmoni_pattern)/pattern_scripting/system_initiative.json  

simple_dialogue:
  default_param:
    trigger_intent: "ciao"
    pattern_scripting: $(find harmoni_pattern)/pattern_scripting/simple_dialogue.json      
    
hass:
  default_param:
    trigger_intent: "{ \"action\":\"check_log\", \"entity\":\"googlehome8554\", \"type\":\"media_player\"}"
    pattern_scripting: $(find harmoni_pattern)/pattern_scripting/hass.json          
