dialogue:
  default_param:
    trigger_intent: "Hey"
    pattern_scripting: $(find harmoni_pattern)/pattern_scripting/dialogue.json

multiple_choice:
  default_param:
    trigger_intent: "Hey"
    pattern_scripting: $(find harmoni_pattern)/pattern_scripting/multiple_choice.json

type_dialogue:
  default_param:
    trigger_intent: "Hey"
    pattern_scripting: $(find harmoni_pattern)/pattern_scripting/type_dialogue.json

listening:
  default_param:
    trigger_intent: "Hey"
    pattern_scripting: $(find harmoni_pattern)/pattern_scripting/listening.json

mic_test:
  default_param:
    trigger_intent: "Hey"
    pattern_scripting: $(find harmoni_pattern)/pattern_scripting/mic_test.json

misty_demo:
  default_param:
    trigger_intent: "Hey"
    pattern_scripting: $(find harmoni_pattern)/pattern_scripting/misty_demo.json
